### ISSUE TITLE
ER: support live filesystem mounts into docker containers

### ISSUE THREAD

**Issue by hagmonk** [docker-archive-public/docker.kitematic#20]
Kitematic uses Unison to sync files between the Docker container and OS X, but it would be more robust to support live filesystem mounts.

Firstly, this means getting the folder on OS X mounted up by the host VM. Unfortunately, boot2docker does not ship with virtualbox host extensions, nor does it ship with an nfs client or other filesystem client which OS X could serve content over (afp, smb, etc). Adding virtualbox extensions seems like it would be the most straightforward solution.

Secondly, Kitematic would need to expose configuration UI for running docker containers with the -v flag. 

Naturally the user has to understand that Docker apps which depend on filesystem mounts are not portable and should only be used for development purposes.

**Comment by james-nesbitt** [comment]
is there any way to still use unison, seeing as vboxdrv is well known for poor performance?
