### ISSUE TITLE
无法打开“Kitematic.app”，因为无法验证开发者。

### ISSUE THREAD

**Issue by airc-ccc** [docker-archive-public/docker.kitematic#5347]
### Expected behavior
I can‘t use Kitematic in my Mac (Catalina)

### Actual behavior

Get the message '无法打开“Kitematic.app”，因为无法验证开发者。
macOS无法验证此App不包含恶意软件。'

### Information about the Issue

Mac OS 10.15
Docker version 19.03.2
Kitematic v0.17.9

### Steps to reproduce the behavior

  1. download kitematic v0.17.9
  2. in mac open it , (My mac is Catalina 10.15)

**Comment by freguinhas** [comment]
From Google Translate:
Unable to open "Kitematic.app" because the developer could not be verified.
macOS cannot verify that this app does not contain malware.

**Comment by freguinhas** [comment]
This is caused by the app not being signed (#5370)
