### ISSUE TITLE
boot2docker/VirtualBox related errors during setup

### ISSUE THREAD

**Issue by Gurpartap** [docker-archive-public/docker.kitematic#56]
Submitting the issue on behalf of @MartinAyla, who experienced some installation problems related to boot2docker and VirtualBox even after reinstalling everything from scratch, including destroying the boot2docker vm (except VirtualBox). Here are some of the logs:

a) https://gist.github.com/MartinAyla/a85eb73a1d0b0c60f10d

```
"VBoxManage: error: Runtime error opening '/Users/martin/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox-tmp' for reading: -102(File not found.).
```

b) https://gist.github.com/MartinAyla/486bb5890bf6fbaaf792

```
"error in run: Failed to initialize machine \"boot2docker-vm\": exit status 1\n"
```

c) https://gist.github.com/MartinAyla/9a4a7129882bcd61e147

```
"VBoxManage: error: The machine 'boot2docker-vm' is already locked for a session (or being unlocked)\nVBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports\nVBoxManage: error: Context: \"LockMachine(a-\u003Esession, LockType_Write)\" at line 462 of file VBoxManageModifyVM.cpp\n"
```

**Comment by evrenkutar** [comment]
i have similar issue with port forwarding (for riak clusters). i poweroff and up vbox and it is solved.
