### ISSUE TITLE
https://github.com/xiyuan-code/jellyfin.gituest canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by la901028** [docker-archive-public/docker.kitematic#5798]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by docker-robott** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem.
If you'd like us to investigate further, could you please open a fresh issue with a more detailed description?
