### ISSUE TITLE
Jenkins:latest doesn't exist

### ISSUE THREAD

**Issue by kalathilajay** [docker-archive-public/docker.kitematic#5805]
### Expected behavior
Runnable version of Jenkins latest should get downloaded and run.

### Actual behavior
Error: jenkins:latest doesn't exist

### Information about the Issue
Seems to have been changes from jenkins:latest to jenkins/jenkins:latest

### Steps to reproduce the behavior

  1. docker run jenkins:latest
  2. or open kitematic dashboard and click or jenkins sample.

**Comment by justincormack** [comment]
You should use jenkins/jenkins now not jenkins.
