### ISSUE TITLE
Is the source for the Docker Desktop Dashboard available anywhere?

### ISSUE THREAD

**Issue by gcobr** [docker-archive-public/docker.kitematic#5814]
I see the announcement on the README file here about this team contributing to the Docker Desktop Dashboard UI that is now shipped with Docker.

Is the source code of that Dashboard macOS app available anywhere?

I understand that is also an Electron App, isn't it?

**Comment by justincormack** [comment]
Hi, no the source of the Docker Desktop Dashboard is not available.
