### ISSUE TITLE
Suggestion: import and display existing images if they existed previous to install of Kitematic

### ISSUE THREAD

**Issue by thesurlydev** [docker-archive-public/docker.kitematic#8]
I would assume that if I had an existing boot2docker VM with images that Kitematic would import and display them. It seems Kitematic has no knowledge of existing images. At the very least, this should be addressed in the documentation.

**Comment by qgicup** [comment]
Still, Kitematic Version 0.5.10 has no knowledge of existing images (that I can usually find via docker images) :( :(
When is gonna be fixed?
