### ISSUE TITLE
Download Virtualbox again?

### ISSUE THREAD

**Issue by petems** [docker-archive-public/docker.kitematic#86]
Do we need to download Virtualbox again if you already have it installed on your machine?

**Comment by luizmendesalmeida** [comment]
Hi.
I ran Kitematic 0.7.4 (Windows alpha) and it didn't find my VirtualBox (4.3.26). The install started to download a new VirtualBox.
Thank you in advance.

**Comment by petems** [comment]
@jeffdm Is there a commit to link where this got fixed?
